# Generated by Django 5.1.3 on 2025-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=255, unique=True)),
                ('property_address', models.CharField(max_length=255)),
                ('market', models.CharField(max_length=255)),
                ('submarket', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('space', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=255)),
                ('access_link', models.URLField(max_length=255)),
            ],
        ),
    ]
