# Generated by Django 5.1.3 on 2025-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_id',
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
