# Generated by Django 5.1.3 on 2025-03-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_rename_property_address_property_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
