# Generated by Django 5.1.3 on 2025-04-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='categories',
            field=models.CharField(default='', max_length=255),
        ),
    ]
