# Generated by Django 5.1.3 on 2025-04-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_property_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='sucess_index',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
