# Generated by Django 5.1.3 on 2025-04-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_property_sucess_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='sucess_index',
            new_name='success_index',
        ),
    ]
