# Generated by Django 5.1.3 on 2025-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_rename_sucess_index_property_success_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Adjusted_Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='RestaurantsPriceRange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='education_density',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='healthcare_density',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='shopping_density',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='transport_density',
            field=models.IntegerField(default=0),
        ),
    ]
